@startuml
hide circle
scale 1.5
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "hosts" as host {
  *id : int
  name : varchar(100)
  address : varchar(100)
}

entity "histories" as history {
  *id : int
  transmitted : int
  received : int
  time : datetime
  *host_id : int <<FK>>
}

host ||--|{ history
@enduml
