@startuml
hide circle
scale 1.5
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "hosts" as host {
  *id : int
  --
  name : varchar(100)
  address : varchar(100)
}

entity "pings" as ping {
  *id : int
  --
  transmitted : int
  received : int
  createAt : datetime
  *host_id : int <<FK>>
}

host ||--|{ ping
@enduml
