@startuml
hide circle
scale 1.5
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "hosts" as host {
  *id : int
  --
  state: int(1)
  hostname : varchar(100)
}

entity "links" as link {
  *id : int
  --
  *host_id : int <<FK>>
  *mac_id : int <<FK>>
}

entity "addresses" as address {
  *id : int
  --
  ip : varchar(100)
  mask : varchar(100)
  version : varchar(2)
  *link_id : int <<FK>>
}

entity "macs" as mac {
  *id : int
  --
  value: varchar(17)
}

link ||--|| mac
link ||--|{ address
host ||--|{ link
@enduml
