@startuml
title GET
hide footbox
skinparam monochrome true

Client -> Server: GET /hosts/3
note right: GET /hosts/3 HTTP/1.1\nHost: http://localhost:3000\n
Server -> Client: HTTP/1.1 200 OK
note left: HTTP/1.1 200 OK\n\n{\n  "name": "DNS Server",\n  "address": "1.1.1.1",\n  "id": 3\n}
@enduml
