@startuml
hide circle
scale 1.5
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "pings" as ping {
  *id : int
  --
  create_at : datetime
}

entity "stats" as stats {
  *id : int
  *ping_id : int
  --
  transmitted : int
  received : int
  time : float
}

ping ||--o| stats
@enduml
