@startuml
hide circle
scale 1.5
skinparam linetype ortho
skinparam monochrome true
left to right direction

entity "hosts" as host {
  id
  --
  name
  address
}

entity "pings" as ping {
  id
  --
  create_at
}

entity "icmps" as icmp {
  id
  --
  seq
  ttl
  time
}

entity "users" as user {
  id
  --
  name
  email
  password
}

host ||--o{ ping
ping ||-upo{ icmp
user ||-upo{ ping
@enduml
